Adding xlink namespace to the svg element declaration used when parseFromString: xmlns:xlink='http://www.w3.org/1999/xlink'
Avoid error in IE 11 when you refer to a symbol in a use statement with
"xlink:href" attribute:
Error: Error parsing XML string
XML5660: The specified prefix has not been declared.